# for local development
version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: 'develop-stage'
    ports:
      - '8080:8080'
    command: /bin/sh -c "yarn serve"
